PL_ENDPOINT = "http://api.football-data.org/v1/soccerseasons/445"
CURRENT_GW = "current"
ALL_GW = "all gameweeks"
RESULTS = "results"
SCHEDULED = "SCHEDULED"
TIMED = "TIMED"
FINISHED = "FINISHED"
LIVE = "IN_PLAY"